### ISSUE TITLE
Timeout.Exception when single-producer job is executed

### ISSUE THREAD

**Issue by sfl0r3nz05** [im-pratham/kafka-perf-testing-k8s#1]
Hi. First of all, thanks for the contribution. I am trying to conduct a performance test on the kafka cluster based on your contribution. 

1. I have deployed a Kafka cluster on Minikube via helm chart: `helm install confluentinc . -n kafka`

<img width="940" alt="kafka" src="https://user-images.githubusercontent.com/6643905/200115987-11d19cf0-b723-4920-9a7f-0843da32cd15.png">

2. As the version of the suggested image (/confluentinc/cp-server:7.0.1) no longer exists, to deploy the `kafka-client` it has been necessary to modify it:

- image: `confluentinc/cp-server:7.2.2.amd64`
- value: `PLAINTEXT://confluentinc-cp-kafka:9092`

```console
apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  labels:
    app: kafka-examples
    purpose: examples
    type: client
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-server:7.2.2.amd64
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    env:
      - name: BOOTSTRAP_SERVERS
        value: PLAINTEXT://confluentinc-cp-kafka:9092
    resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: '1'
          memory: 1Gi
```

3. **KHOST** is collected: `KHOST=$(kubectl get svc -n kafka -o jsonpath="{.items[1].metadata.name}")`
```console
echo $KHOST
confluentinc-cp-kafka
```

4. **KPORT** is collected: `KPORT=$(kubectl get svc -n kafka -o jsonpath="{.items[1].spec.ports[0].port}")`
```console
echo $KPORT
9092
```

5. Both values are combined:

```console
export KAFKA=$KHOST:$KPORT
echo $KAFKA
confluentinc-cp-kafka:9092
```

6. The topic is created, although the image used in the kafka-client (`cp-server:7.2.2.amd64`) does not contain the configuration file (`/etc/kafka/config/client.properties`), it does contain the file (`/etc/kafka/server.properties`), so the topic could be deployed.

```console
kubectl exec -it kafka-client -n kafka -- kafka-topics --bootstrap-server $KAFKA --create --topic ssl-perf-test --partitions 6 --replication-factor 3 --config retention.ms=1800000 --config min.insync.replicas=2 --command-config /etc/kafka/server.properties
```

7.  I have to modify the `single-producer.yaml` due to errors with the original image:

```console
      containers:
        - name: kafka-client
          image: confluentinc/cp-server:7.2.2.amd64
          env:
            - name: BOOTSTRAP_SERVERS
              value: PLAINTEXT://confluentinc-cp-kafka:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "confluentinc-cp-zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://confluentinc-cp-zookeeper:5556
```

8. I have launched `kubectl apply -f single-producer.yaml -n kafka`

```console
configmap/kafka-single-producer-perf-script unchanged
job.batch/kafka-single-producer-client created
```
9. Kafka producer is running, but the job is never completed:

```console
NAME                                                   READY   STATUS    RESTARTS       AGE
pod/kafka-single-producer-client--1-lz9kt              1/1     Running   0              84s

NAME                                     COMPLETIONS   DURATION   AGE
job.batch/kafka-single-producer-client   0/1           88s        90s
```

10. At the end, I get this exception: `org.apache.kafka.common.errors.TimeoutException: Call has timed out. Callback: fetchMetadata`.

11. I leave here the link to the huge [log](https://github.com/im-pratham/kafka-perf-testing-k8s/files/9943654/log.txt) obtained.

Any suggestion?

**Comment by im-pratham** [comment]
can you verify in `single-producer.yaml`, the command section is not modified, and it matches with - 
```yaml
          command:
            - sh
            - -c
            - "/script/perf-script.sh"
```
Looking at attached log files, it seems like the command settings was not there, and client is trying to run default script, i.e. running itself as a kafka broker.

**Comment by sfl0r3nz05** [comment]
Thanks for the response.

I have added the suggested command and this is the result:

```console
kubectl logs pod/kafka-single-producer-client--1-bfprb -n kafka
sh: /script/perf-script.sh: No such file or directory
```

I guess it is because the image does not contain the file `/script//script/perf-script.sh`.

```console
image: confluentinc/cp-server:7.2.2.amd64
```

Could you suggest some images?

**Comment by im-pratham** [comment]
You must have for forgot to add volume and volumeMMount in yaml. You can run https://github.com/im-pratham/kafka-perf-testing-k8s/blob/main/single-producer.yaml as it is, and that would work. 
It creates configmap with data `perf-script.sh` (line 1 to 25) and then creates volume with this configMap and attached to the POD (line 62-66 and 58-60)

**Comment by sfl0r3nz05** [comment]
Thanks again for the response. 

As you can see when I have used [single-producer.yaml](https://github.com/im-pratham/kafka-perf-testing-k8s/blob/main/single-producer.yaml) updating the environments:

```console
- name: BOOTSTRAP_SERVERS
   value: PLAINTEXT://confluentinc-cp-kafka:9092
- name: KAFKA_ZOOKEEPER_CONNECT
   value: "confluentinc-cp-zookeeper:2181"
- name: KAFKA_ADVERTISED_LISTENERS
   value: PLAINTEXT://confluentinc-cp-zookeeper:5556
```

I have received that the `configmap` is `unchanged`:

```console
configmap/kafka-single-producer-perf-script unchanged
job.batch/kafka-single-producer-client created
```

```console
pod/kafka-single-producer-client--1-g7pzz              0/1     Error     0              4m21s
```

This is the output of `kubectl describe` command:

```console
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    2m29s               default-scheduler  Successfully assigned kafka/kafka-single-producer-client--1-g7pzz to minikube
  Normal   Pulled       2m13s               kubelet            Container image "confluentinc/cp-server:7.0.1" already present on machine
  Normal   Created      2m4s                kubelet            Created container kafka-client
  Normal   Started      2m3s                kubelet            Started container kafka-client
  Warning  FailedMount  97s (x4 over 100s)  kubelet            MountVolume.SetUp failed for volume "kafka-perf-script" : object "kafka"/"kafka-single-producer-perf-script" not registered
```

This a piece of `kubectl logs` command output:

```console
1000
usage: producer-performance [-h] --topic TOPIC --num-records NUM-RECORDS
                            [--payload-delimiter PAYLOAD-DELIMITER]
                            --throughput THROUGHPUT
                            [--producer-props PROP-NAME=PROP-VALUE [PROP-NAME=PROP-VALUE ...]]
                            [--producer.config CONFIG-FILE]
                            [--print-metrics]
                            [--transactional-id TRANSACTIONAL-ID]
                            [--transaction-duration-ms TRANSACTION-DURATION]
                            (--record-size RECORD-SIZE |
                            --payload-file PAYLOAD-FILE)
producer-performance:  error:  argument   --producer.config:  expected  one argument
```

**Comment by im-pratham** [comment]
Thanks for the details. I will retest and give you details by tomorrow EOD

**Comment by sfl0r3nz05** [comment]
Thanks again. I was wrong. I have deleted a previous `configmap` created and updated `--producer.config /etc/kafka/producer.properties` option of the `perf-script.sh`.

```console
pod/kafka-single-producer-client--1-8nc9c              0/1     Completed   0              3m23s
```

```console
job.batch/kafka-single-producer-client   1/1           3m11s      3m23s
```

```console
1000
4975 records sent, 990.2 records/sec (0.94 MB/sec), 118.8 ms avg latency, 1425.0 ms max latency.
10000 records sent, 980.007840 records/sec (0.93 MB/sec), 79.18 ms avg latency, 1425.00 ms max latency, 25 ms 50th, 403 ms 95th, 443 ms 99th, 446 ms 99.9th.
```

Thanks a lot for your recommendations. Now, I will close the issue.
